name: env_beampy_torch
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - asttokens=2.2.1=pyhd8ed1ab_0
  - backcall=0.2.0=pyh9f0ad1d_0
  - backports=1.0=pyhd8ed1ab_3
  - backports.functools_lru_cache=1.6.4=pyhd8ed1ab_0
  - beamngpy=1.25.1=pyhd8ed1ab_0
  - blas=1.0=mkl
  - brotlipy=0.7.0=py310h2bbff1b_1002
  - bzip2=1.0.8=he774522_0
  - ca-certificates=2023.5.7=h56e8100_0
  - certifi=2023.5.7=pyhd8ed1ab_0
  - cffi=1.15.1=py310h2bbff1b_3
  - charset-normalizer=2.0.4=pyhd3eb1b0_0
  - colorama=0.4.6=pyhd8ed1ab_0
  - cryptography=39.0.1=py310h21b164f_0
  - cuda-cccl=12.2.53=0
  - cuda-cudart=11.8.89=0
  - cuda-cudart-dev=11.8.89=0
  - cuda-cupti=11.8.87=0
  - cuda-libraries=11.8.0=0
  - cuda-libraries-dev=11.8.0=0
  - cuda-nvrtc=11.8.89=0
  - cuda-nvrtc-dev=11.8.89=0
  - cuda-nvtx=11.8.86=0
  - cuda-profiler-api=12.2.53=0
  - cuda-runtime=11.8.0=0
  - cycler=0.11.0=pyhd8ed1ab_0
  - debugpy=1.5.1=py310hd77b12b_0
  - decorator=5.1.1=pyhd8ed1ab_0
  - executing=1.2.0=pyhd8ed1ab_0
  - filelock=3.9.0=py310haa95532_0
  - freetype=2.10.4=h546665d_1
  - idna=3.4=py310haa95532_0
  - importlib-metadata=6.6.0=pyha770c72_0
  - importlib_metadata=6.6.0=hd8ed1ab_0
  - intel-openmp=2023.1.0=h57928b3_46319
  - ipykernel=6.15.0=pyh025b116_0
  - ipython=8.13.2=pyh08f2357_0
  - jedi=0.18.2=pyhd8ed1ab_0
  - jinja2=3.1.2=pyhd8ed1ab_1
  - jpeg=9e=h8ffe710_2
  - jupyter_client=8.2.0=pyhd8ed1ab_0
  - jupyter_core=5.3.0=py310h5588dad_0
  - kiwisolver=1.4.4=py310h476a331_0
  - libblas=3.9.0=16_win64_mkl
  - libcblas=3.9.0=16_win64_mkl
  - libcublas=11.11.3.6=0
  - libcublas-dev=11.11.3.6=0
  - libcufft=10.9.0.58=0
  - libcufft-dev=10.9.0.58=0
  - libcurand=10.3.3.53=0
  - libcurand-dev=10.3.3.53=0
  - libcusolver=11.4.1.48=0
  - libcusolver-dev=11.4.1.48=0
  - libcusparse=11.7.5.86=0
  - libcusparse-dev=11.7.5.86=0
  - libffi=3.4.2=hd77b12b_6
  - liblapack=3.9.0=16_win64_mkl
  - libnpp=11.8.0.86=0
  - libnpp-dev=11.8.0.86=0
  - libnvjpeg=11.9.0.86=0
  - libnvjpeg-dev=11.9.0.86=0
  - libpng=1.6.37=h1d00b33_2
  - libsodium=1.0.18=h8d14728_1
  - libtiff=4.2.0=h0c97f57_3
  - libuv=1.44.2=h2bbff1b_0
  - libwebp=1.2.4=h8ffe710_0
  - libwebp-base=1.2.4=h8ffe710_0
  - lz4-c=1.9.3=h8ffe710_1
  - m2w64-gcc-libgfortran=5.3.0=6
  - m2w64-gcc-libs=5.3.0=7
  - m2w64-gcc-libs-core=5.3.0=7
  - m2w64-gmp=6.1.0=2
  - m2w64-libwinpthread-git=5.0.0.4634.697f757=2
  - markupsafe=2.1.1=py310he2412df_1
  - matplotlib-base=3.4.3=py310h79a7439_2
  - matplotlib-inline=0.1.6=pyhd8ed1ab_0
  - mkl=2022.1.0=h6a75c08_874
  - mpmath=1.2.1=py310haa95532_0
  - msgpack-python=1.0.4=py310h476a331_0
  - msys2-conda-epoch=20160418=1
  - nest-asyncio=1.5.6=pyhd8ed1ab_0
  - networkx=2.8.4=py310haa95532_1
  - numpy=1.23.2=py310h8a5b91a_0
  - openssl=1.1.1q=h8ffe710_0
  - packaging=23.1=pyhd8ed1ab_0
  - parso=0.8.3=pyhd8ed1ab_0
  - pickleshare=0.7.5=py_1003
  - pillow=9.4.0=py310hd77b12b_0
  - pip=23.0.1=py310haa95532_0
  - platformdirs=3.5.0=pyhd8ed1ab_0
  - prompt-toolkit=3.0.38=pyha770c72_0
  - prompt_toolkit=3.0.38=hd8ed1ab_0
  - psutil=5.9.0=py310h2bbff1b_0
  - pure_eval=0.2.2=pyhd8ed1ab_0
  - pycparser=2.21=pyhd3eb1b0_0
  - pygments=2.15.1=pyhd8ed1ab_0
  - pyopengl=3.1.6=pyhd8ed1ab_1
  - pyopenssl=23.0.0=py310haa95532_0
  - pyparsing=3.0.9=pyhd8ed1ab_0
  - pysocks=1.7.1=py310haa95532_0
  - python=3.10.0=h96c0403_3
  - python-dateutil=2.8.2=pyhd8ed1ab_0
  - python_abi=3.10=2_cp310
  - pytorch=2.0.1=py3.10_cuda11.8_cudnn8_0
  - pytorch-cuda=11.8=h24eeafa_5
  - pytorch-mutex=1.0=cuda
  - pywin32=305=py310h2bbff1b_0
  - pyzmq=25.0.2=py310hd77b12b_0
  - requests=2.29.0=py310haa95532_0
  - scipy=1.8.1=py310h7c00807_2
  - setuptools=66.0.0=py310haa95532_0
  - six=1.16.0=pyh6c4a22f_0
  - sqlite=3.41.2=h2bbff1b_0
  - stack_data=0.6.2=pyhd8ed1ab_0
  - sympy=1.11.1=py310haa95532_0
  - tbb=2021.5.0=h2d74725_1
  - tk=8.6.12=h2bbff1b_0
  - tornado=6.2=py310he2412df_0
  - traitlets=5.9.0=pyhd8ed1ab_0
  - typing-extensions=4.5.0=hd8ed1ab_0
  - typing_extensions=4.5.0=pyha770c72_0
  - tzdata=2023c=h04d1e81_0
  - urllib3=1.26.16=py310haa95532_0
  - vc=14.2=h21ff451_1
  - vs2015_runtime=14.27.29016=h5e58377_2
  - wcwidth=0.2.6=pyhd8ed1ab_0
  - wheel=0.38.4=py310haa95532_0
  - win_inet_pton=1.1.0=py310haa95532_0
  - xz=5.2.10=h8cc25b3_1
  - zeromq=4.3.4=h0e60522_1
  - zipp=3.15.0=pyhd8ed1ab_0
  - zlib=1.2.13=h8cc25b3_0
  - zstd=1.5.0=h6255e5f_0
  - pip:
      - apptools==5.2.0
      - attrs==23.1.0
      - blinker==1.6.2
      - ccimport==0.4.2
      - click==8.1.3
      - configargparse==1.5.3
      - configobj==5.0.8
      - cumm-cu118==0.4.10
      - dash==2.9.3
      - dash-core-components==2.0.0
      - dash-html-components==2.0.0
      - dash-table==5.0.0
      - easydict==1.10
      - envisage==7.0.3
      - fastjsonschema==2.16.3
      - fire==0.5.0
      - flask==2.3.2
      - install==1.3.5
      - ipywidgets==8.0.6
      - itsdangerous==2.1.2
      - jsonschema==4.17.3
      - jupyterlab-widgets==3.0.7
      - lark==1.1.5
      - mayavi==4.8.1
      - nbformat==5.7.0
      - ninja==1.11.1
      - open3d==0.17.0
      - pccm==0.4.8
      - plotly==5.14.1
      - portalocker==2.7.0
      - pybind11==2.10.4
      - pyface==8.0.0
      - pyopengl-accelerate==3.1.6
      - pyqt5==5.15.9
      - pyqt5-qt5==5.15.2
      - pyqt5-sip==12.12.1
      - pyrsistent==0.19.3
      - pyyaml==6.0
      - tenacity==8.2.2
      - termcolor==2.3.0
      - torchaudio==2.0.2
      - torchvision==0.15.2
      - traits==6.4.1
      - traitsui==7.4.3
      - vtk==9.2.6
      - werkzeug==2.3.4
      - widgetsnbextension==4.0.7
prefix: D:\anaconda3\envs\env_beampy_torch
