name: env_carla0913_torch
channels:
  - pytorch
  - nvidia
  - defaults
dependencies:
  - blas=1.0=mkl
  - brotlipy=0.7.0=py38h2bbff1b_1003
  - ca-certificates=2023.08.22=haa95532_0
  - certifi=2023.7.22=py38haa95532_0
  - cffi=1.15.1=py38h2bbff1b_3
  - charset-normalizer=2.0.4=pyhd3eb1b0_0
  - cryptography=39.0.1=py38h21b164f_0
  - cuda-cccl=12.2.53=0
  - cuda-cudart=11.8.89=0
  - cuda-cudart-dev=11.8.89=0
  - cuda-cupti=11.8.87=0
  - cuda-libraries=11.8.0=0
  - cuda-libraries-dev=11.8.0=0
  - cuda-nvrtc=11.8.89=0
  - cuda-nvrtc-dev=11.8.89=0
  - cuda-nvtx=11.8.86=0
  - cuda-profiler-api=12.2.53=0
  - cuda-runtime=11.8.0=0
  - filelock=3.9.0=py38haa95532_0
  - freetype=2.12.1=ha860e81_0
  - giflib=5.2.1=h8cc25b3_3
  - icc_rt=2022.1.0=h6049295_2
  - idna=3.4=py38haa95532_0
  - intel-openmp=2023.1.0=h59b6b97_46319
  - jinja2=3.1.2=py38haa95532_0
  - jpeg=9e=h2bbff1b_1
  - lerc=3.0=hd77b12b_0
  - libcublas=11.11.3.6=0
  - libcublas-dev=11.11.3.6=0
  - libcufft=10.9.0.58=0
  - libcufft-dev=10.9.0.58=0
  - libcurand=10.3.3.53=0
  - libcurand-dev=10.3.3.53=0
  - libcusolver=11.4.1.48=0
  - libcusolver-dev=11.4.1.48=0
  - libcusparse=11.7.5.86=0
  - libcusparse-dev=11.7.5.86=0
  - libdeflate=1.17=h2bbff1b_0
  - libnpp=11.8.0.86=0
  - libnpp-dev=11.8.0.86=0
  - libnvjpeg=11.9.0.86=0
  - libnvjpeg-dev=11.9.0.86=0
  - libpng=1.6.39=h8cc25b3_0
  - libtiff=4.5.0=h6c2663c_2
  - libuv=1.44.2=h2bbff1b_0
  - libwebp=1.2.4=hbc33d0d_1
  - libwebp-base=1.2.4=h2bbff1b_1
  - lz4-c=1.9.4=h2bbff1b_0
  - markupsafe=2.1.1=py38h2bbff1b_0
  - mkl=2023.1.0=h8bd8f75_46356
  - mkl-service=2.4.0=py38h2bbff1b_1
  - mkl_fft=1.3.6=py38hf11a4ad_1
  - mkl_random=1.2.2=py38hf11a4ad_1
  - mpmath=1.2.1=py38haa95532_0
  - networkx=2.8.4=py38haa95532_1
  - numpy=1.24.3=py38h79a8e48_1
  - numpy-base=1.24.3=py38h8a87ada_1
  - openssl=1.1.1w=h2bbff1b_0
  - packaging=23.1=py38haa95532_0
  - pillow=9.4.0=py38hd77b12b_0
  - pip=23.1.2=py38haa95532_0
  - pooch=1.7.0=py38haa95532_0
  - pycparser=2.21=pyhd3eb1b0_0
  - pyopenssl=23.0.0=py38haa95532_0
  - pysocks=1.7.1=py38haa95532_0
  - python=3.8.0=hff0d562_2
  - pytorch=2.0.1=py3.8_cuda11.8_cudnn8_0
  - pytorch-cuda=11.8=h24eeafa_5
  - pytorch-mutex=1.0=cuda
  - requests=2.29.0=py38haa95532_0
  - scipy=1.10.1=py38hdcfc7df_1
  - setuptools=67.8.0=py38haa95532_0
  - sqlite=3.41.2=h2bbff1b_0
  - sympy=1.11.1=py38haa95532_0
  - tbb=2021.8.0=h59b6b97_0
  - tk=8.6.12=h2bbff1b_0
  - typing_extensions=4.6.3=py38haa95532_0
  - urllib3=1.26.16=py38haa95532_0
  - vc=14.2=h21ff451_1
  - vs2015_runtime=14.27.29016=h5e58377_2
  - wheel=0.38.4=py38haa95532_0
  - win_inet_pton=1.1.0=py38haa95532_0
  - xz=5.4.2=h8cc25b3_0
  - zlib=1.2.13=h8cc25b3_0
  - zstd=1.5.5=hd43e919_0
  - pip:
      - ansi2html==1.8.0
      - apptools==5.2.1
      - asttokens==2.2.1
      - attrs==23.1.0
      - backcall==0.2.0
      - carla==0.9.13
      - ccimport==0.4.2
      - click==8.1.6
      - colorama==0.4.6
      - comm==0.1.3
      - configargparse==1.5.5
      - configobj==5.0.8
      - contourpy==1.1.0
      - cumm-cu118==0.4.10
      - cycler==0.11.0
      - dash==2.11.1
      - dash-core-components==2.0.0
      - dash-html-components==2.0.0
      - dash-table==5.0.0
      - debugpy==1.6.7
      - decorator==5.1.1
      - easydict==1.10
      - envisage==7.0.3
      - executing==1.2.0
      - fastjsonschema==2.17.1
      - fire==0.5.0
      - flask==2.2.5
      - fonttools==4.41.0
      - importlib-metadata==6.8.0
      - importlib-resources==6.0.0
      - ipykernel==6.24.0
      - ipython==8.12.2
      - ipywidgets==8.0.7
      - itsdangerous==2.1.2
      - jedi==0.18.2
      - jsonschema==4.18.4
      - jsonschema-specifications==2023.7.1
      - jupyter-client==8.3.0
      - jupyter-core==5.3.1
      - jupyterlab-widgets==3.0.8
      - kiwisolver==1.4.4
      - lark==1.1.6
      - matplotlib==3.7.2
      - matplotlib-inline==0.1.6
      - mayavi==4.8.1
      - nbformat==5.7.0
      - nest-asyncio==1.5.6
      - ninja==1.11.1
      - open3d==0.17.0
      - parso==0.8.3
      - pccm==0.4.8
      - pickleshare==0.7.5
      - pkgutil-resolve-name==1.3.10
      - platformdirs==3.9.1
      - plotly==5.15.0
      - portalocker==2.7.0
      - prompt-toolkit==3.0.39
      - psutil==5.9.5
      - pure-eval==0.2.2
      - pybind11==2.11.1
      - pyface==8.0.0
      - pygments==2.15.1
      - pyparsing==3.0.9
      - pyqt5==5.15.9
      - pyqt5-qt5==5.15.2
      - pyqt5-sip==12.12.1
      - pyquaternion==0.9.9
      - python-dateutil==2.8.2
      - pytorch3d==0.7.4
      - pywin32==306
      - pyyaml==6.0.1
      - pyzmq==25.1.0
      - referencing==0.30.0
      - retrying==1.3.4
      - rpds-py==0.9.2
      - six==1.16.0
      - spconv-cu118==2.3.6
      - stack-data==0.6.2
      - tabulate==0.9.0
      - tenacity==8.2.2
      - termcolor==2.3.0
      - torchaudio==2.0.2
      - torchvision==0.15.2
      - tornado==6.3.2
      - tqdm==4.66.1
      - traitlets==5.9.0
      - traits==6.4.1
      - traitsui==8.0.0
      - vtk==9.2.6
      - wcwidth==0.2.6
      - werkzeug==2.2.3
      - widgetsnbextension==4.0.8
      - yacs==0.1.8
      - zipp==3.16.2
prefix: D:\anaconda3\envs\env_carla0913_torch
